# roles/hosts/tasks/main.yml
---

- name: Install custom {{ hosts_file }} file
  template:
    src: etc/hosts.j2
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ host_file_backup }}"
  become: true
  notify: hosts changed
  tags: hosts
